### ISSUE TITLE
Form is null on get request

### ISSUE THREAD

**Issue by totalagility** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#10]
Form is null on get request. 

Needs this check, sames code as manual credit card payment in PaymentManualViewComponent.cs:

 //set postback values (we cannot access "Form" with "GET" requests)
            if (this.Request.Method != WebRequestMethods.Http.Get)

Request
{Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest}
    Body: {Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream}
    ContentLength: null
    ContentType: null
    Cookies: {Microsoft.AspNetCore.Http.Internal.RequestCookieCollection}
    Form: '((Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest)Request).Form' threw an exception of type 'System.InvalidOperationException'
    HasFormContentType: false
    Headers: {Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestHeaders}
    Host: {localhost:15539}
    HttpContext: {Microsoft.AspNetCore.Http.DefaultHttpContext}
    IsHttps: false
    Method: "GET"
    Path: {/checkout/paymentinfo}
    PathBase: {}

**Comment by skoshelev** [comment]
Closed #10
