### ISSUE TITLE
'payments.authorizenet' plugin is not compatible or cannot be loaded. nopcommerce 4.10 

### ISSUE THREAD

**Issue by Cbrown35** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#12]
'payments.authorizenet' plugin is not compatible or cannot be loaded. nopcommerce 4.10 . Any work around or fix for this?

**Comment by AndreiMaz** [comment]
nopCommerce 4.10 is not released yet

**Comment by Cbrown35** [comment]
Wow, my apologies. Now wondering what breach I pulled this from. Is there a release posted date?

**Comment by AndreiMaz** [comment]
beginning of july
