### ISSUE TITLE
MD5 Hash End of Life & Signature Key Replacement

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#14]
Authorize.Net is phasing out the MD5 based hash use for transaction response verification in favor of the SHA-512 based hash utilizing a Signature Key. If your existing integrations or clients are using MD5 hash, they will need to move to using the SHA-512 based hash. This applies to all Authorize.Net integration methods including the Authorize.Net API, AIM, SIM/DPM and Relay Response. 

Will the AuthorizeNet.dll have to be updated with this plugin? It looks like it's expecting the MD5 hashes.

Thanks
-Cameron

**Comment by skoshelev** [comment]
Waite for this ticket https://github.com/AuthorizeNet/sdk-dotnet/issues/247

**Comment by skoshelev** [comment]
![image](https://user-images.githubusercontent.com/16875599/51831018-39509580-2302-11e9-8729-fb3b92b7ff5e.png)

**Comment by cklenk** [comment]
@skoshelev Yes that is what I was talking about.

**Comment by skyleraustin** [comment]
Any update?

**Comment by skyleraustin** [comment]
Is this repository not maintained? If no update is going to be made to support this change, your users need to know to find alternative solutions.

**Comment by skoshelev** [comment]
Hi @skyleraustin.
With this repository everything is fine, we are working on replacing SDK, if you really watch to the ticket, you should know that SDK was updated only 5 days ago. We'll update our plugin as soon as possible

**Comment by skoshelev** [comment]
We updated Authorize.Net SDK in our plugin for nopCommerce 3.70-4.00 versions. Version of plugin for nopCommerce 4.10 will work without any changes. You may reload a new plugin from [our marketplace.](https://www.nopcommerce.com/p/2320/authorizenet-payment-module.aspx) 

Closed #14
