### ISSUE TITLE
3D Secure Procedure (3DS) support

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#18]
The EU's second Payment Services Policy (2015/2366 PSD2) aims to ensure consumer protection for all payment methods and to promote a payment landscape with even more openness.
One of the key requirements of PSD2 is the "Strong Customer Authentication" (SCA), which, starting in September 2019 https://ec.europa.eu/info/law/payment-services-psd-2-directive-eu-2015-2366_en

In concrete terms, this means that as of this date, credit card payments may only be processed using the 3D Secure Procedure (3DS).

**Comment by skoshelev** [comment]
3D Secure not supported by Authorize.Net
