### ISSUE TITLE
Automatically process recurring payments from Authorize.NET 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#2]
Forum source: http://www.nopcommerce.com/boards/t/13795/authorizenet-recurring-support-manual.aspx

**Comment by skoshelev** [comment]
Resolved (commit [#b9c7543](https://github.com/nopSolutions/Authorize.Net-plugin-for-nopcommerce/commit/b9c7543500442f4f5af65f6a94bc2ea583447fce))
