### ISSUE TITLE
ARB does not seem to be submitting valid requests in 4.0

### ISSUE THREAD

**Issue by lifebio** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#22]
In nopcommerce 4.0, the ARB submissions do not appear to be correct.
Using the authorize.net live console, then capturing the xml that is sent, the following error is returned:
E00045 : The root node does not reference a valid XML namespace.

When running the site live, the error captured is null and just returns a vague error 1, unknown. message.

**Comment by skoshelev** [comment]
Can't reproduce on the latest version

Closed #22
