### ISSUE TITLE
Port the plugin to .Net 5

### ISSUE THREAD

**Issue by r3tec** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#23]
Do you have any plans to port the plugin to NET 5.0 or later? We are migrating to NOP 4.4 without expectation that this plugin will work. What do you think?

**Comment by r3tec** [comment]
I tried building the plugin as part of 4.4. solution. On the surface, all changes are related to applying asynchronous processing. I can go ahead and update the implementation to do just that. Would you be interested in me contributing here?

**Comment by AndreiMaz** [comment]
yes, we plan to upgrade it in the near time
