### ISSUE TITLE
Enforce character limits for customerAddressType

### ISSUE THREAD

**Issue by ted-phillips** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#25]
nopCommerce address form field entries can exceed the character count limitations for "customerAddressType" in the Authorize.net API, see "Request Field Description" section here: [https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card](url) 

For example, a customer may enter a lengthy street address greater than 60 characters in length, which will result in this error:  

> Error while placing order. Error 1: Payment error: Error #E00003: The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:address' element is invalid - The value XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value..
 
This error is output to the browser, which is less than ideal.  

My first thought was to create an AddressValidator class with length rules for each customer address property required for "BillTo" and "ShipTo" (firstName, lastName, email, address, city, etc.), however, I do not think it is a good idea to fail the payment processing and force the customer to go back and edit their addresses (which may be 100% correct) simply because they exceed the API limits.  

A better approach might be to silently truncate the customerAddressType properties similar to how you do it for the "[x_invoice_num](https://github.com/nopSolutions/Authorize.Net-plugin-for-nopcommerce/blob/898fdf8046cce70dd3a026d43ce65f2b19dd53aa/Nop.Plugin.Payments.AuthorizeNet/AuthorizeNetPaymentProcessor.cs#L342)"

Only the numeric portion of the street address and the ZipPostalCode are required for Authorize.net's address verification (AVS), so truncating a lengthy address should be of little harm.  It is doubtful that any customer would enter a ZipPostalCode greater than 20 characters, but we should enforce the limit on all the fields anyway.

Since the address properties are not guaranteed to exceed their API limitations using .Substring() may be unwieldy, instead we could make use of the Truncate string extension method in [GetTransactionRequestAddress ](https://github.com/nopSolutions/Authorize.Net-plugin-for-nopcommerce/blob/898fdf8046cce70dd3a026d43ce65f2b19dd53aa/Nop.Plugin.Payments.AuthorizeNet/AuthorizeNetPaymentProcessor.cs#L169):

```
        private static customerAddressType GetTransactionRequestAddress(Address address)
        {
            var transactionRequestAddress = new customerAddressType
            {
                firstName = address.FirstName.Truncate(50),
                lastName = address.LastName.Truncate(50),
                email = address.Email.Truncate(50),
                address = address.Address1.Truncate(60),
                city = address.City.Truncate(40),
                zip = address.ZipPostalCode.Truncate(20)
            };

            if (!string.IsNullOrEmpty(address.Company))
                transactionRequestAddress.company = address.Company.Truncate(50);

            if (address.StateProvince != null)
                transactionRequestAddress.state = address.StateProvince.Abbreviation;

            if (address.Country != null)
                transactionRequestAddress.country = address.Country.TwoLetterIsoCode;

            return transactionRequestAddress;
        }
```

If you agree with this approach I would be happy to submit a PR.

**Comment by skoshelev** [comment]
Hi @ted-phillips. Thanks for the suggestion, we implemented it ourselves using our own method

Closed #25
