### ISSUE TITLE
AuthorizeNet dll

### ISSUE THREAD

**Issue by ethankershaw** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#27]
I began looking into what would be required here to support Nop 4.5 and got tripped up on not being sure where the AuthorizeNet.dll file in this repo comes from. Authorize.Net only has a ["beta" of their SDK](https://github.com/AuthorizeNet/dotnet-core-sdk-beta) for modern .Net, with some others having forked that to develop it further. 

So my questions are: 
- Who created the AuthorizeNet.dll?
- What is it's license?
- It was [updated for 4.3](https://github.com/nopSolutions/Authorize.Net-plugin-for-nopcommerce/commit/3d9086e235b07056aa80058dac8600fca1967287#diff-eb64af69f3f81317ab1f70e05f6996fdb69d7875a2d22df1c664b622c87bf304) but not for 4.4, maybe it is still current/compatible. If not - what work items would there be?

**Comment by skoshelev** [comment]
We build AuthorizeNet.dll ourselves from the sources https://github.com/AuthorizeNet/dotnet-core-sdk-beta, the source code of the official Authorize.Net SDK is distributed under the MIT license, we do not make any changes to it, we only correct incompatible places with the new version of .Net. In fact, this is the same SDK only manually rebuilt by us
