### ISSUE TITLE
Error when attempting partial refund

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#28]
> While testing the Authorize.net plugin(version 2.38) in NOP 4.60.3 (both via local debugging in VS and also via a test instance installed on a webserver), I'm getting the following error when attempting to process a partial refund from the NOP order screen back to Authorize.net (note that I'm using the Authorize.net sandbox) -
> 
> `System.NullReferenceException: Object reference not set to an instance of an object. at Nop.Plugin.Payments.AuthorizeNet.AuthorizeNetPaymentProcessor.RefundAsync(RefundPaymentRequest refundPaymentRequest) at Nop.Services.Payments.PaymentService.RefundAsync(RefundPaymentRequest refundPaymentRequest) in .....\Libraries\Nop.Services\Payments\PaymentService.cs:line 252 at Nop.Services.Orders.OrderProcessingService.PartiallyRefundAsync(Order order, Decimal amountToRefund) in ...\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 2939`

Source: https://www.nopcommerce.com/boards/topic/97932/nop-4603-authorizenet-error-when-attempting-partial-refund

**Comment by skoshelev** [comment]
In version 4.70 we added a more meaningful error in case the payment process was completed in a way not intended by the plugin

Closed #28
