### ISSUE TITLE
Email and Phone not being sent to Authorize.net

### ISSUE THREAD

**Issue by michaelw-guru** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#29]
Neither Email nor phone is being sent to Authorize.net. This is causing an issue with Authroize.net having the email set as required data for a transaction. This was tested using the Nopcommerce store and going to both Authorize.net sandbox and live. When going over the logs there is no errors in Nopcommerce. Also, Nopcommerce order is showing that the billing address and shipping address have the email and phone. If the Authorize.net email and phone is marked as not required than the transaction goes through. Our system does require to have the data in Authorize.net so just marking the fields as not required is not an option. The process that was used to check out in Nopcommerce was as a guest using valid live data for card and contact information. 

This is an urgent issue as it is causing production outages.

Nopcommerce is 4.60.4  (Self-hosted on Azure)
Authorize.net plugin is 2.38

**Comment by AndreiMaz** [comment]
https://www.nopcommerce.com/en/boards/topic/98589/authorizenet-plugin-not-sending-email-or-phone-to-authorizenet-from-nopcommerce

**Comment by skoshelev** [comment]
Hi @michaelw-guru. I checked the source code and I don’t quite understand the problem you are having if an email is specified in the user’s billing address, we [transfer it to the Authorize.net side](https://github.com/nopSolutions/Authorize.Net-plugin-for-nopcommerce/blob/nopcommerce-4.60/Nop.Plugin.Payments.AuthorizeNet/AuthorizeNetPaymentProcessor.cs#L179) along with the rest of the data. In the part of the API that we use, the billing address is the only object that provides for the transmission of email. In the next version we will also transmit the phone number

Closed #29
