### ISSUE TITLE
Will this plugin be affected by Authorize.net's upcoming certificate authority change?

### ISSUE THREAD

**Issue by bmercernccer** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#30]
Authorize.net is switching their provider to Digicert and has published documentation on what developers need to do to accommodate this change. Is it safe to assume that this plugin will not be affected by this change?

https://support.authorize.net/knowledgebase/Knowledgearticle/?code=KA-05545

**Comment by AndreiMaz** [comment]
No, it won't
