### ISSUE TITLE
Refund not working/Errors in Log

### ISSUE THREAD

**Issue by SofusMunch** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#5]
The refund function doesn't seem to be functioning properly. It will set the payment as refunded in the shop, while not actually refunding in authorize. I'm running 3.80.

Also my log is full of:

"Authorize.NET: Order cannot be loaded (order GUID: 71250483-be11-4798-b548-622161ac157f)"

Looking at the code the error in question only seems to appear during processing of recurring payments, something we do not use.

Did I configure something incorrectly?

Edit: Never mind the first part, refund **is** working.  Still wondering about the errors though.

**Comment by skoshelev** [comment]
This error may appear only in one case, when the Authorize.NET server has a recurring order that was deleted from the database of the nopCommerce, all you need to do is stop the recurring payment on the Authorize.NET server

Closed #5
