### ISSUE TITLE
Refund vs. Void

### ISSUE THREAD

**Issue by woodronnie** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#6]
I have noticed that while using the Authorize.net plugin, once a credit card payment is processed successfully the status at Authorize.net is "Captured/Pending Settlement".  "Void" only shows up on nonCommerce when the status is "Authorized" so will not work correctly.  You can't "Refund" a payment in this status at Authorize.Net, you can only "Void" the transaction.  The status changes to "Settled" once their batch has run at the end of day processing.  

While the status is "Captured/Pending Settlement" you have to "Void" the transaction, you can't "Refund" it.  Wouldn't it be better to check in the "Refund" method and see if the transaction needs to be voided or refunded according to the status at Authorize.Net?

**Comment by skoshelev** [comment]
Closed #6
