### ISSUE TITLE
Authorize.NET: Order cannot be loaded error in Log

### ISSUE THREAD

**Issue by sumo300** [nopSolutions/Authorize.Net-plugin-for-nopcommerce#7]
After upgrading to nopCommerce 3.9 and the latest version of this plug-in, I see a lot of Errors in the log with the following message and URL.

Authorize.NET: Order cannot be loaded error
https://[siteURL]/plugins/paymentauthorizenet/ipnhandler

Why is this happening and is it something to be concerned about?  There are no other details in the log other than the order GUID it happened for.

If I look up the order in question, I see that the AuthorizationTransactionResult is "Approved (1: This transaction has been approved.)" and has an AuthorizationTransactionId and an AuthorizationTransactionCode.

**Comment by skoshelev** [comment]
Could not reproduce for nopCommerce version 4.10

Closed #7
